[build-system]
requires = ["setuptools == 68.2.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "us_vis"
version = "0.1"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
	"./us_vis/test.py"
]
